### ISSUE TITLE
Adguardhome has upgraded the requirement that a rule line can not exceed 1024 bytes

### ISSUE THREAD

**Issue by monsm** [DoingDog/XXKiller#10]
https://github.com/AdguardTeam/AdGuardHome/issues/6003

So your rules can not be added to the new adguardhome, please update your rules

**Comment by CyrusHou** [comment]
same issue, adg version is v0.108.0-b.41

**Comment by DoingDog** [comment]
https://github.com/AdguardTeam/AdGuardHome/issues/6003

This issue has been fixed by the developers of AdGuard Home, and it has been updated in the latest Edge test version. It will be updated in the official version soon.

**Comment by CyrusHou** [comment]
以收到,谢谢

**Comment by CyrusHou** [comment]
以收到,谢谢
